version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql-pass}"
      MYSQL_DATABASE: cafe
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: my_db_files
        target: /var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8080:8080"

volumes:
  my_db_files::
